### ISSUE TITLE
texto en LECB_RN

### ISSUE THREAD

**Issue by rpuig2001** [vatspa/Operaciones#558]
![image](https://github.com/user-attachments/assets/855ae424-499d-4bef-ab3e-9370c50d8573)
tendria que salir 245-660, ya que no soy xal, soy RN

**Comment by ImAlex28** [comment]
![image](https://github.com/user-attachments/assets/670f6dc8-1d91-4010-9a91-c90aa9547ba6)
Diría que estaba bien puesto. LLI cubre ese sector por encima de 305.

**Comment by ImAlex28** [comment]
![image](https://github.com/user-attachments/assets/16eecc31-21e9-445b-bec4-6f5d7eb7ae19)
![image](https://github.com/user-attachments/assets/386fddcf-9b15-4d53-b20a-0ab9e16db2be)

**Comment by rpuig2001** [comment]
Entonces LLI asumido por RS, esto es lo que ve RS:
![image](https://github.com/user-attachments/assets/5891b234-88c3-422d-8347-822d57406147)

**Comment by ImAlex28** [comment]
![image](https://github.com/user-attachments/assets/dc672b08-323d-4ae6-a6c2-ea40a83ef3e3)
Corregido para LLI y RS.

**Comment by ImAlex28** [comment]
![image](https://github.com/user-attachments/assets/22a39c9c-a6c2-4894-9189-7a59f2b3327d)
Y corregido para PPI y RN
